### ISSUE TITLE
部分问题

### ISSUE THREAD

**Issue by dongyuechuwu** [hei-jack/heypass#1]
首先，感谢作者的辛苦付出，程序真的很棒！

1.用户名为什么不允许使用纯数字呢？手机号码更好记啊；
2.如何关闭二次验证呢？或者有个开关，允许用户自主选择。不能自定义内容的方式，手机上使用时感受非常差；
3.首页应该允许设置直接跳转到登录页面或者添加一个按钮，不然真的很繁琐。

以上拙见，再次感谢您的付出！

**Comment by hei-jack** [comment]
抱歉，平时不咋登账号，现在才看到。
感谢你对这个不成熟作品的认可，针对你提的三个建议，我逐一回复一下。

1、这个纯粹是担心有些小白到时候设置个6位纯密码的账号和密码，如果弱口令被爆破了，那该多恐怖。
2、二次验证就是为了加强安全系数，但确实是牺牲了用户的便捷性。我自己用的时候也经常能感觉到当时这个项目设计之初的很多不足，有时间会考虑接入谷歌验证器之类的或者借鉴弥补便捷性。
3、首页设置了跳转登录页面，其实就暴露了登录入口，还是容易造成安全隐患，以后可能会直接屏蔽首页。

总体而言，这个作品当时写的主要是自用目前还有很多不足，建议别在公网环境使用。
至于你提的建议，我基本是采纳了，但是目前暂时没有时间改。
可能以后会考虑用go重构，但是目前尚未提上日程。
如果你要是等不及，也可以fork到自己的私有仓库二开。
